export const PageNames = {
  entranceTabs: 'entranceTabs',
  home: 'home',
  searchHouse: 'searchHouse',
  house: 'house',
  fav: 'fav',
  sell: 'sell',
  agent: 'agent',
  'agent-detail': 'agent-detail',
  job: 'job',
  'job-detail': 'job-detail',
  more: 'more',
  signIn: 'signIn',
  chatroom: 'chatroom',
  photoLibrary: 'photoLibrary',
  imageViewer: 'imageViewer',
  userContact: 'userContact',
} as const;
